### ISSUE TITLE
 Importação de dados do site do investidor (b3) 

### ISSUE THREAD

**Issue by gilcleis** [alexsilva/b3irpf#2]
conforme o README entrei no site da https://www.investidor.b3.com.br e baixei o extrato em Excel com as notas de negociação do ano e baixei o extrato em Excel com todos os provendos/outros recebidos.

só não consigo importar para os b3irpf 

não encontro na tela administração (Negociações).
importar com o comando importar lista de dados os dados do arquivo Excel.

![image](https://github.com/alexsilva/b3irpf/assets/72532864/b88b1811-4454-43e9-97da-2146585352b4)

**Comment by alexsilva** [comment]
No menu "Negociações" / Opções "Ações em Grupo" / importar lista de dados.

Desta lista você precisa excluir ativos de renda fixa como cdbs (no b3 investidor dá para filtrar). E de preferência já ter os ativos registrados no menu "Ativos", assim como corretoras.

A tela você exibiu aqui é de Bonificação e um pouco acima tem Negociações.

Tem que melhorar vários aspectos do programa ainda.

**Comment by alexsilva** [comment]
Hoje mesmo eu cheguei implementar um comando para criar [Widgets](https://github.com/alexsilva/b3irpf/commit/3bd5a5ad77f6d7c2f1d0aa21bcd2db1f6d6e8db5) que são links para facilitar a navegação.
Não sei se chegou a receber essa atualização mas se atualizar, basta executar setup_project para criar os links.
